name: Python CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  format:
    uses: chartboost/ruff-action@v1
    with:
      args: 'format --check'

  publish:
    uses: microsoft/action-python/.github/workflows/publish.yml@0.6.4
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
